version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    ports:
     - "127.0.0.1:5000:5000"
    depends_on:
     - "mangodb"
     
  frontend:
    build:
     context: .
     dockerfile: reactjs.Dockerfile
    ports:
     - "127.0.0.1:5050:5050"
    depends_on:
     - "mangodb"

  mangodb:
    image: mongo
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - 'mongo:/data/db'
    environment:
      - MONGO_INITDB_DATABASE=gitlab_data
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass

volumes:
  mongo:

  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   volumes:
  #     - './frontend:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
